[build]
  command = "npm run build"
  publish = "build"

# Opt out of Google's FLoC network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
